# run: ga .github/workflows/main.yml && privatcommit -m "Working" && gps && gsleep 1s && open "https://github.com/snipem/monako/actions"
name: Build Monako
on: [pull_request] # only run on pull requests for now
# on: [push, pull_request]
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.14.x]
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go-version }}

    - name: Setup Ruby for use with actions
      uses: actions/setup-ruby@v1.0.0

    - name: setup env
      shell: bash
      run: |
        echo "::set-env name=GOPATH::${{ github.workspace }}/../go"
        echo "::add-path::${{ github.workspace }}/../go/bin"

    - name: Checkout code
      uses: actions/checkout@v2

    - name: dependencies
      run: make --always-make deps

    - name: optional dependencies
      run: make --always-make optional_deps

    - name: debug2
      run: find / | grep asciidoctor

    - name: Fetch Theme
      run: make --always-make theme

    - name: test
      run: make --always-make test

    # - name: coverage
    #   uses: paambaati/codeclimate-action@v2.5.5
    #   with:
    #     coverageCommand: go tool cover -func=c.out
    #     debug: true

    - name: build
      run: make --always-make build

    - name: Run Monako and compose site
      run: make --always-make compose