name: release

on:
  push:
    tags:
      - v*

jobs:
  test:
    strategy:
      matrix:
        go-version: [1.14.x]
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}

    steps:

    # Go setup
    - name: Install Go
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go-version }}
    - name: Setup env
      shell: bash
      run: |
        echo "::set-env name=GOPATH::${{ github.workspace }}/../go"
        echo "::add-path::${{ github.workspace }}/../go/bin"
    - name: Checkout code
      uses: actions/checkout@v2

    # Monako setup

    - name: Dependencies
      run: make --always-make deps test_deps theme

    # GoReleaser

    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v1
      with:
        version: latest
        args: release --rm-dist
        key: ${{ secrets.YOUR_PRIVATE_KEY }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

