on:
  push:
    tags:
      - v*
    branches:
      - develop-release #for testing this

jobs:
  test:
    strategy:
      matrix:
        go-version: [1.14.x]
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Build
      uses: goreleaser/goreleaser-action@v1

    - name: Dependencies
      run: make --always-make deps theme

    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v1
      with:
        version: latest
        args: release --rm-dist
        key: ${{ secrets.YOUR_PRIVATE_KEY }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

